theme: minima
title: Solving the Pyramix Duo
author: Vivethen Balachandiran
email: vbala2@ocdsb.ca
description: >
  My solve times for the pyramix duo. Includes the date and time needed for of each attempt.
  
github_username: Vivethen
